[package]
name = "rk"
version = "0.1.0"
authors = ["dsbrgg <dsbrgg@gmail.com>"]
edition = "2018"

[dependencies]
dialoguer = "0.5.0"
dirs = "2.0"
rand = "^0.3"
hex = "0.3.2"
serde = "1.0"
serde_yaml = "0.8"
aes-soft = "0.3.3"
block-modes = "0.3.3"
crypto-hash = "0.3.4"
clap = "2.33.0"
